apiVersion: v1
kind: Namespace
metadata:
  name: seeocr

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: seeocr-kafka-cm
  namespace: seeocr
data:
  kafka_host: 172.21.0.4
  kafka_port: "19092"
  seeocr_topic_input: "seeocr_input"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: seeocr-pv-nfs
  namespace: seeocr
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/k8s-nfs
    server: 172.21.0.4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seeocr-pvc-nfs
  namespace: seeocr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi

