kind: Service
apiVersion: v1
metadata:
  name: seeocr-post-service
  namespace: seeocr
spec:
  selector:
    app: seeocr-post-app
  ports:
    - port: 21616
      targetPort: 2828

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: seeocr-post-deployment
  namespace: seeocr
  labels:
    app: seeocr-post-app
spec:
  selector:
    matchLabels:
      app: seeocr-post-app
  replicas: 1
  template:
    metadata:
      labels:
        app: seeocr-post-app
        log: seeocr
    spec:
      containers:
        - name: seeocr-post
          image: hzcsk8s.io/seeocr_paddle_cpu
          imagePullPolicy: Always
          ports:
            - containerPort: 2828
          command: ["/bin/bash"]
          args: ["-c", "python3 app_service.py --task seeocr.post"]

          env:
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: seeocr-kafka-cm
                  key: kafka_host

            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: seeocr-kafka-cm
                  key: kafka_port

          resources:
            requests:
              memory: "2.5Gi"
              cpu: "0.8"
            limits:
              memory: "3Gi"
              cpu: "0.8"

          livenessProbe:
            exec:
              command: ["test", "-e", "/tmp/healthy"]
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 20
            failureThreshold: 3

          volumeMounts:
            - name: k8s-nfs
              mountPath: /data
              subPath: seeocr

      volumes:
        - name: k8s-nfs
          persistentVolumeClaim:
            claimName: seeocr-pvc-nfs

      restartPolicy: Always
      terminationGracePeriodSeconds: 10
