FROM hzcsk8s.io/opencv_cpu

WORKDIR /app
EXPOSE 2828
ENV PYTHONPATH=/app

RUN apt update \
    && $APT_INSTALL \
        iputils-ping net-tools \
        curl \
    && rm -rf /var/lib/apt/lists/* \
    && $PIP_INSTALL \
        flask \
        flask_cors \
        kafka-python \
        python-snappy \
        cos-python-sdk-v5 \
        shapely pyclipper \
    && python3 -m pip install paddlepaddle==2.4.0rc0 -i https://pypi.tuna.tsinghua.edu.cn/simple

ADD ckpts /ckpts
ADD app /app
